// Generated by gencpp from file hlpr_speech_msgs/SpeechService.msg
// DO NOT EDIT!


#ifndef HLPR_SPEECH_MSGS_MESSAGE_SPEECHSERVICE_H
#define HLPR_SPEECH_MSGS_MESSAGE_SPEECHSERVICE_H

#include <ros/service_traits.h>


#include <hlpr_speech_msgs/SpeechServiceRequest.h>
#include <hlpr_speech_msgs/SpeechServiceResponse.h>


namespace hlpr_speech_msgs
{

struct SpeechService
{

typedef SpeechServiceRequest Request;
typedef SpeechServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpeechService
} // namespace hlpr_speech_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hlpr_speech_msgs::SpeechService > {
  static const char* value()
  {
    return "8f7ae7a65dc30cceb3e782937b879015";
  }

  static const char* value(const ::hlpr_speech_msgs::SpeechService&) { return value(); }
};

template<>
struct DataType< ::hlpr_speech_msgs::SpeechService > {
  static const char* value()
  {
    return "hlpr_speech_msgs/SpeechService";
  }

  static const char* value(const ::hlpr_speech_msgs::SpeechService&) { return value(); }
};


// service_traits::MD5Sum< ::hlpr_speech_msgs::SpeechServiceRequest> should match
// service_traits::MD5Sum< ::hlpr_speech_msgs::SpeechService >
template<>
struct MD5Sum< ::hlpr_speech_msgs::SpeechServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hlpr_speech_msgs::SpeechService >::value();
  }
  static const char* value(const ::hlpr_speech_msgs::SpeechServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hlpr_speech_msgs::SpeechServiceRequest> should match
// service_traits::DataType< ::hlpr_speech_msgs::SpeechService >
template<>
struct DataType< ::hlpr_speech_msgs::SpeechServiceRequest>
{
  static const char* value()
  {
    return DataType< ::hlpr_speech_msgs::SpeechService >::value();
  }
  static const char* value(const ::hlpr_speech_msgs::SpeechServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hlpr_speech_msgs::SpeechServiceResponse> should match
// service_traits::MD5Sum< ::hlpr_speech_msgs::SpeechService >
template<>
struct MD5Sum< ::hlpr_speech_msgs::SpeechServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hlpr_speech_msgs::SpeechService >::value();
  }
  static const char* value(const ::hlpr_speech_msgs::SpeechServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hlpr_speech_msgs::SpeechServiceResponse> should match
// service_traits::DataType< ::hlpr_speech_msgs::SpeechService >
template<>
struct DataType< ::hlpr_speech_msgs::SpeechServiceResponse>
{
  static const char* value()
  {
    return DataType< ::hlpr_speech_msgs::SpeechService >::value();
  }
  static const char* value(const ::hlpr_speech_msgs::SpeechServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HLPR_SPEECH_MSGS_MESSAGE_SPEECHSERVICE_H
