// Generated by gencpp from file hlpr_speech_msgs/SpeechServiceResponse.msg
// DO NOT EDIT!


#ifndef HLPR_SPEECH_MSGS_MESSAGE_SPEECHSERVICERESPONSE_H
#define HLPR_SPEECH_MSGS_MESSAGE_SPEECHSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hlpr_speech_msgs
{
template <class ContainerAllocator>
struct SpeechServiceResponse_
{
  typedef SpeechServiceResponse_<ContainerAllocator> Type;

  SpeechServiceResponse_()
    : speech_cmd()  {
    }
  SpeechServiceResponse_(const ContainerAllocator& _alloc)
    : speech_cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _speech_cmd_type;
  _speech_cmd_type speech_cmd;





  typedef boost::shared_ptr< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechServiceResponse_

typedef ::hlpr_speech_msgs::SpeechServiceResponse_<std::allocator<void> > SpeechServiceResponse;

typedef boost::shared_ptr< ::hlpr_speech_msgs::SpeechServiceResponse > SpeechServiceResponsePtr;
typedef boost::shared_ptr< ::hlpr_speech_msgs::SpeechServiceResponse const> SpeechServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator1> & lhs, const ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.speech_cmd == rhs.speech_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator1> & lhs, const ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hlpr_speech_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66b8c3f2415da3d1e6bf60087f6cab82";
  }

  static const char* value(const ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66b8c3f2415da3d1ULL;
  static const uint64_t static_value2 = 0xe6bf60087f6cab82ULL;
};

template<class ContainerAllocator>
struct DataType< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hlpr_speech_msgs/SpeechServiceResponse";
  }

  static const char* value(const ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#response values\n"
"string speech_cmd\n"
"\n"
;
  }

  static const char* value(const ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speech_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hlpr_speech_msgs::SpeechServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "speech_cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.speech_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HLPR_SPEECH_MSGS_MESSAGE_SPEECHSERVICERESPONSE_H
