// Generated by gencpp from file hlpr_speech_msgs/StampedString.msg
// DO NOT EDIT!


#ifndef HLPR_SPEECH_MSGS_MESSAGE_STAMPEDSTRING_H
#define HLPR_SPEECH_MSGS_MESSAGE_STAMPEDSTRING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hlpr_speech_msgs
{
template <class ContainerAllocator>
struct StampedString_
{
  typedef StampedString_<ContainerAllocator> Type;

  StampedString_()
    : stamp()
    , keyphrase()  {
    }
  StampedString_(const ContainerAllocator& _alloc)
    : stamp()
    , keyphrase(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _keyphrase_type;
  _keyphrase_type keyphrase;





  typedef boost::shared_ptr< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> const> ConstPtr;

}; // struct StampedString_

typedef ::hlpr_speech_msgs::StampedString_<std::allocator<void> > StampedString;

typedef boost::shared_ptr< ::hlpr_speech_msgs::StampedString > StampedStringPtr;
typedef boost::shared_ptr< ::hlpr_speech_msgs::StampedString const> StampedStringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hlpr_speech_msgs::StampedString_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hlpr_speech_msgs::StampedString_<ContainerAllocator1> & lhs, const ::hlpr_speech_msgs::StampedString_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.keyphrase == rhs.keyphrase;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hlpr_speech_msgs::StampedString_<ContainerAllocator1> & lhs, const ::hlpr_speech_msgs::StampedString_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hlpr_speech_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dab84539140abbb7370c583798723196";
  }

  static const char* value(const ::hlpr_speech_msgs::StampedString_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdab84539140abbb7ULL;
  static const uint64_t static_value2 = 0x370c583798723196ULL;
};

template<class ContainerAllocator>
struct DataType< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hlpr_speech_msgs/StampedString";
  }

  static const char* value(const ::hlpr_speech_msgs::StampedString_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Stamped string message to be used in speech recognition\n"
"\n"
"#Time stamp\n"
"time stamp\n"
"#Detected keyphrase\n"
"string keyphrase\n"
;
  }

  static const char* value(const ::hlpr_speech_msgs::StampedString_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.keyphrase);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StampedString_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hlpr_speech_msgs::StampedString_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hlpr_speech_msgs::StampedString_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "keyphrase: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.keyphrase);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HLPR_SPEECH_MSGS_MESSAGE_STAMPEDSTRING_H
